# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0366e4914d15cc2a8f268e357e01c63e5769e6999caef8bc1c6a0d22faf4d879a4b3622d82993cfb1fd3c1551f9983f5f454d20e69e94b8191a2d75d0b6ff45a

test:
  secret_key_base: d5bd9fd0603b6873e3c688f3ebfb8fecb5c6f669ac1a22608aff36a22c62e8fbe5487033aacfc02411591839a8631ae2ffae46e42ecf6a599bd6ebe9512c73bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
